version: '3.8'

services:
  xms:
    build: .
    container_name: xms
    ports:
      - "9528:9528"
    volumes:
      - ./media:/app/media
      - ./config:/app/config
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
